---
title: "Outbreak report template"
author: ""
date: ""
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

## Report

This is a living document to gather functions and code snippets that eventually will evolve into an outbreak report template (+ package(s)).

```{r}
# as a starting point
main_dataset <- outbreaks::fluH7N9_china_2013
```


### Time

```{r}
library(incidence)
inc_week_7 <- incidence(main_dataset$date_of_onset, interval = 7)
```

```{r}
plot(inc_week_7)
```

```{r}
inc_week_7 <- incidence(main_dataset$date_of_onset, 
                        interval = 7, 
                        groups = main_dataset$gender)
plot(inc_week_7, show_cases = TRUE, border = "black")
```


### Place


### Person



#### Single variable analysis

```{r, eval = TRUE}
# Inspired by Daniel Gardiner
# https://github.com/DanielGardiner/UsefulFunctions/blob/efffde624d424d977651ed1a9ee4430cbf2b0d6f/single.variable.analysis.v0.3.R#L12
# just a quick prototype for RR

outcome <- main_dataset$outcome == "Death"
is_male <- main_dataset$gender == "m"
is_child <- as.integer(main_dataset$age) <= 12

univariate_analysis <- function (outcome, ...) {
  n <- length(outcome)
  predictors <- list(...)
  predictor_labels <- substitute(list(...))
  predictor_labels <- vapply(predictor_labels[-1L], deparse, character(1L))
  stopifnot(length(predictors) > 0L, 
            all(vapply(predictors, length, integer(1L)) == n),
            all(vapply(predictors, is.logical, logical(1L))))
  na_rows <- Reduce(function (acc, el) acc | is.na(el), predictors, init = FALSE)
  n_na_rows <- sum(na_rows)
  
  if (n_na_rows) {
    warning("Removed ", n_na_rows, " rows due to missing values")
  }
  
  res <- lapply(predictors, function (predictor) {
    table <- epitools::epitable(outcome[!na_rows], 
                                predictor[!na_rows])    
    #odds <- epitools::oddsratio(table, method = "wald") # what method?
    rr <- epitools::riskratio(table, method = "wald")
    midp_pval_rr <- rr$p.value[2L, 1L]
 
    cbind(
      data.frame(
        exp = rr$data[3L, 2L],
        exp_cases = rr$data[2L, 2L],
        exp_AR = round(rr$data[2L, 2L] / rr$data[3L, 2L], 1L),
        unexp = rr$data[1L, 3L],
        unexp_cases = rr$data[1L, 2L],
        unexp_AR = round(rr$data[1L, 2L] / rr$data[1L, 3L], 1L)
      ),
      t(rr$measure[2L, ]),
      data.frame(p_value = midp_pval_rr)
    )
  })
  
  cbind(
    data.frame(exposure = predictor_labels),
    do.call(rbind, res)
  )
}


res <- univariate_analysis(outcome, is_male, is_child)
knitr::kable(res)


```

#### Case Fatality Rate

```{r}

case_fatality_rate <- function (deaths, population, conf_level = 0.95) {
  res <- binom::binom.wilson(deaths, population, conf.level = conf_level)
  res <- res[, c("x", "n", "mean", "lower", "upper")]
  colnames(res) <- c("deaths", "population", "cfr", "lower", "upper")
  res
}

known_status <- main_dataset[!is.na(main_dataset$outcome), ]
deaths <- sum(known_status$outcome == "Death")
population <- length(main_dataset$outcome)


case_fatality_rate(deaths, population) %>% knitr::kable()
```

CFR by region

```{r}
group_by(known_status, province) %>%
  do({
    deaths <- sum(.$outcome == "Death")
    population <- length(.$outcome)
    case_fatality_rate(deaths, population)
  }) %>%
  arrange(desc(lower)) %>%
  knitr::kable()
```


## CI Helper

Just a prototype for the idea

```{r}
str_rate <- function(o, n, conf_level = 0.95, method = "wilson") {
  stopifnot(length(method) == 1L, is.character(method))
  stopifnot(length(conf_level) == 1L, is.numeric(conf_level))
  stopifnot(length(o) == 1L, is.numeric(o), 0 <= o)
  stopifnot(length(n) == 1L, is.numeric(n), o <= n)
  res <- binom::binom.confint(
    o, n,
    conf.level = conf_level,
    methods = method
  )
  # 71.30%; 95% CI 65.03-77.57%
  percent <- scales::percent_format(accuracy = 0.01)
  percent_wo_suffix <- scales::percent_format(accuracy = 0.01, suffix = "")
  paste0(
    percent(res$mean),
    "; ", scales::percent(conf_level, accuracy = 1),
    " CI ", percent_wo_suffix(res$lower), " ",  percent(res$upper)
  )
}
res <- str_rate(1, 5)
```

The case fatality rate low (`r str_rate(1, 5)`).
